### ISSUE TITLE
[QUESTION] Cannot get init to complete

### ISSUE THREAD

**Issue by kingmesal** [mrmattwilkins/google-contacts-sync#13]
I've tried about everything and am scratching my head.

I have a gmail account and a gsuite account. I have my credentials for people api access setup. I have deleted all contacts in account A, exported all contacts from account B and imported into account A.

I keep getting errors:
`HttpError 404 when requesting https://people.googleapis.com/v1/people:createContact?alt=json returned "Requested entity was not found.". Details: "Requested entity was not found."`

I get that error on both `update` and `add` methods.

Any ideas what might be going on here?

**Comment by mrmattwilkins** [comment]
Hi Jim,
No idea off the top of my head.  But could you post more context, there
must be a lot more output than the above?  It would help refresh my memory
of which bit of code is generating the error.
The error might be because of what you did regarding deleting and exporting
and importing, probably confused the process somewhat.  Anyway a bit more
context might help me,
Thanks
Matt

**Comment by kingmesal** [comment]
I had run init numerous times and it kept failing with the same errors... so I thought, starting with the identical lists on both sides should ensure they are the same. So deleting everything and importing a single list into both, but then that failed too... Given that both lists were never synced and identical I would expect no errors, but that is not where I am at.

The branch of code is in the init section where it can call add, update or update_tag
```
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://people.googleapis.com/v1/people/c5246339937754554183:updateContact?updatePersonFields=addresses%2Cbiographies%2Cbirthdays%2CclientData%2CemailAddresses%2Cevents%2CexternalIds%2Cgenders%2CimClients%2Cinterests%2Clocales%2Clocations%2Cmemberships%2CmiscKeywords%2Cnames%2Cnicknames%2Coccupations%2Corganizations%2CphoneNumbers%2Crelations%2CsipAddresses%2Curls%2CuserDefined&alt=json returned "Requested entity was not found.". Details: "Requested entity was not found.">
```

**Comment by mrmattwilkins** [comment]
Can you post the full stack trace, or isn't there an exception thrown?

**Comment by kingmesal** [comment]
```
Traceback (most recent call last):
  File "/home/me/google-contacts-sync/sync.py", line 249, in <module>
    raise err
  File "/home/me/google-contacts-sync/sync.py", line 244, in <module>
    otheracc.update(p['tag'], newcontact, args.verbose)
  File "/home/me/google-contacts-sync/contacts.py", line 427, in update
    raise err
  File "/home/me/google-contacts-sync/contacts.py", line 416, in update
    self.service.people().updateContact(
  File "/home/me/miniconda3/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ne/miniconda3/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
   ```

**Comment by mrmattwilkins** [comment]
Thanks.  I can see from the line numbers that we are running different versions.  Can you do a git pull and try again please?  I doubt it will fix the problem, but at least we will be on the same version.
Cheers

**Comment by kingmesal** [comment]
I just added code to get better error logging and to separate the 429
errors from those 404.
